title: CSV-Datei filtern
question: |
  Erweitere die Funktion `create_persons_from_csv` um einen Parameter
  `csv_filter`, mit dem man einen Teil der Elemente aus der CSV herausgefiltert wird.
  Achte darauf, dass die Funktion auch noch funktioniert, wenn kein `csv_filter` gesetzt ist.

  ```python
  def no_underaged(name, age):
      return age >= 18


  persons = Person.create_persons_from_csv("persons.csv", no_underaged)

  for person in persons:
      print(person)
  # Swantje,32
  # Niko,31
  # Sven,38
  ```

tip: |
  Erinnere dich, wie man Funktionen als Parameter übergeben hat
  und diese dann ausgeführt hat.

solution: |
  ```python
  from csv import reader, writer

  class Person:
      def __init__(self, name, age):
          self.name = name
          self.age = age

      def __eq__(self, other):
          return isinstance(other, Person) and self.name == other.name and self.age == other.age

      def __str__(self):
          return f"Person: {self.name}, {self.age}"

      @classmethod
      def create_persons_from_csv(cls, file_path, csv_filter=None):
          result = list()
          with open(file_path) as csv_file:
              for zeile in reader(csv_file):
                  name, age = zeile
                  age = int(age)
                  if csv_filter is None or csv_filter(name, age):
                      result.append(cls(name, age))

          return result

      def save_to_csv(self, file_path, mode="a"):
          with open(file_path, mode, newline="") as csv_file:
              writer(csv_file).writerow([self.name, self.age])

  # Beispielnutzung:
  def no_underaged(name, age):
      return age >= 18

  csv_file_path = "persons.csv"
  persons = Person.create_persons_from_csv(csv_file_path, no_underaged)

  for person in persons:
      print(person)
  ```

  Diese Lösung erweitert die `create_persons_from_csv`-Methode um den optionalen `csv_filter`-Parameter. Wenn ein Filter übergeben wird, wird er auf jede Zeile der CSV-Datei angewendet. Nur wenn der Filter `True` zurückgibt (oder wenn kein Filter gesetzt ist), wird eine neue `Person`-Instanz erstellt und zur Ergebnisliste hinzugefügt.

  Beachten Sie, dass das Alter zu einem Integer konvertiert wird, bevor es an den Filter übergeben oder zur Erstellung einer `Person`-Instanz verwendet wird. Dies stellt sicher, dass der Vergleich im `no_underaged`-Filter korrekt funktioniert.
