title: Verschachteltes Dictionary analysieren
question: |
  Gegeben sei ein verschachteltes Dictionary, das Daten von Studenten und ihren Noten in verschiedenen F채chern enth채lt. Schreibe ein Programm, das f체r jeden Studenten den Durchschnitt seiner Noten berechnet und diesen ausgibt. Nutze Schleifen, um durch das Dictionary zu iterieren.

  Beispiel f체r das Dictionary:
  ```python
  studenten = {
      "Anna": {"Mathe": 1, "Englisch": 2},
      "Max": {"Mathe": 3, "Englisch": 2}
  }
  ```
solution: |
  ```python
  studenten = {
      "Anna": {"Mathe": 1, "Englisch": 2},
      "Max": {"Mathe": 3, "Englisch": 2}
  }

  for name, faecher in studenten.items():
      durchschnitt = sum(faecher.values()) / len(faecher)
      print(f"{name}: Durchschnittsnote = {durchschnitt:.2f}")
  ```
