title: Nicht-leere Strings
question: |
  Filtere eine Liste von Strings und behalte nur die nicht-leeren bei.
solution: |
  ```python
  nicht_leer = [s for s in ["Hallo", "", "Welt", ""] if s]
  print(nicht_leer)
  ```