title: Listen mit Zahlen definieren
question: |
  Definieren Sie eine Liste mit den Zaheln von `#!python 0` bis `#!python 8`. Speichern Sie diese in eine 
  Variable namens `spielfeld`.
solution: |
  ```python
  spielfeld = [0, 1, 2, 3, 4, 5, 6, 7, 8] 
  ```
solution_video: https://www.youtube.com/embed/qjEblfG4EKY?si=q_aobBn0BysR6t2N
