title: Verschachtelung
question: |
  Erstelle List Comprehensions für den folgenden Code:

  ```python
  a = [(0, 0), (0, 1), (0, 2), (0, 3), (1, 0), (1, 1), (1, 2), (1, 3)]

  b = [[0, 0, 0, 0], [0, 1, 2, 3], [0, 2, 4, 6], [0, 3, 6, 9]]

  c = [['aA', 'bA', 'cA'], ['aB', 'bB', 'cB'], ['aC', 'bC', 'cC']]
  ```
solution: |
  ```python
  a = [(i,j) for i in range(2) for j in range(4)]

  b = [[i*j for i in range(4)] for j in range(4)]

  c = [[i+j for i in "abc"] for j in "ABC"]

  print(a)
  print(b)
  print(c)
  ```
