title: "Multiple Lines Plot"
question: |

  Erstelle ein Diagramm mit zwei Linien auf derselben Achse:
  
    1. Eine Sinuswelle unter Verwendung der numpy-sin-Funktion
    2. Eine Kosinuswelle unter Verwendung der numpy-cos-Funktion
  
  Verwende x-Werte von -2π bis 2π.
  Füge eine Legende hinzu um die beiden Linien zu unterscheiden.

tip: "Verwende np.linspace um gleichmäßig verteilte x-Werte zu erstellen und vergiss nicht, numpy zu importieren."

solution: |
  ```python
  import matplotlib.pyplot as plt
  import numpy as np

  x = np.linspace(-2*np.pi, 2*np.pi, 100)
  y_sin = np.sin(x)
  y_cos = np.cos(x)

  plt.plot(x, y_sin, label='sin(x)')
  plt.plot(x, y_cos, label='cos(x)')
  
  plt.title("Sine and Cosine Waves")
  plt.xlabel("x")
  plt.ylabel("y")
  plt.legend()
  plt.show()
  ```
